/*
 * Freeze muse's icon vocabulary into the package.
 *
 * `iconify-icon` fetches its glyph data from api.iconify.design at runtime. For a suite whose
 * product promise is "zéro dépendance cloud", the design system reaching out to a CDN to draw a
 * chevron is the wrong shape — and it is also why every icon is a 0×0 box for the first few
 * hundred milliseconds of a page.
 *
 * This pulls the paths once, at author time, and commits them. Run it after adding a key to
 * `icons.ts`; `icons-data.test.ts` fails the build if the two ever disagree.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const LIB = join(import.meta.dir, '../src/lib');

const source = readFileSync(join(LIB, 'icons.ts'), 'utf8');
const names = [...source.matchAll(/'([a-z-]+:[a-z0-9-]+)'/g)].map((m) => m[1]);
const unique = [...new Set(names)].sort();

const byPrefix = new Map<string, string[]>();
for (const full of unique) {
    const [prefix, name] = full.split(':');
    byPrefix.set(prefix, [...(byPrefix.get(prefix) ?? []), name]);
}

type Entry = { body: string; width: number; height: number };
const out: Record<string, Entry> = {};
const licences: string[] = [];

for (const [prefix, list] of byPrefix) {
    const url = `https://api.iconify.design/${prefix}.json?icons=${list.join(',')}`;
    const data = await fetch(url).then((r) => r.json());

    /* The filtered `?icons=` response carries no `info`, so the licence comes from the
       collections endpoint. Bundling artwork without recording its terms is the mistake the
       shipped trial font already cost this repo once. */
    const info = await fetch(`https://api.iconify.design/collections?prefix=${prefix}`)
        .then((r) => r.json())
        .then((c) => c[prefix]);
    if (!info?.license?.spdx) throw new Error(`no licence metadata for ${prefix} — refusing to bundle it`);

    const w = data.width ?? 24;
    const h = data.height ?? 24;
    licences.push(
        `${info.name} by ${info.author?.name ?? 'unknown'} — ${info.license.title} (${info.license.spdx})\n    ${info.license.url ?? ''}`
    );

    for (const name of list) {
        const icon = data.icons?.[name];
        if (!icon) throw new Error(`${prefix}:${name} is not in the ${prefix} collection`);
        out[`${prefix}:${name}`] = {
            body: icon.body,
            width: icon.width ?? w,
            height: icon.height ?? h
        };
    }
}

const missing = unique.filter((n) => !out[n]);
if (missing.length) throw new Error(`no data for ${missing.join(', ')}`);

const file = `/*
 * Generated by \`scripts/build-icons.ts\` — do not edit by hand.
 *
 * The glyph data for every name in \`icons.ts\`, frozen into the package so nothing is fetched
 * from api.iconify.design at runtime. Re-run the script after adding a key.
 *
 * Attribution for the bundled artwork is in LICENSE, and is not optional: Solar is CC BY 4.0.
 */
export type IconData = { body: string; width: number; height: number };

export const ICON_DATA: Record<string, IconData> = ${JSON.stringify(out, null, 4)};
`;

writeFileSync(join(LIB, 'icons-data.ts'), file);
console.log(`${unique.length} icons bundled from ${byPrefix.size} collection(s)`);
console.log(licences.map((l) => '  ' + l).join('\n'));
